name: dowallet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  json_annotation: ^4.9.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  drift_dev: ^2.26.1

flutter:
  uses-material-design: true
